kind: pipeline
name: default

steps:
  - name: test
    image: ruby
    commands:
      - gem install bundler:1.17.2
      - bundle install
      - rspec

---
kind: pipeline
name: textlint
steps:
  - name: textlint
    image: node
    commands:
      - npm install textlint
      - npm install textlint-rule-preset-ja-technical-writing
      - $(npm bin)/textlint --format pretty-error --preset ja-technical-writing README.md

---
kind: pipeline
name: gotest
steps:
  - name: gotest
    image: golang
    commands:
      - go mod init hello.go
      - go build
      - go test